# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mam_single <- function(y, theta, b, a, c, g, K) {
    .Call(`_sirtmm_mam_single`, y, theta, b, a, c, g, K)
}

mam_d <- function(y, theta, b, a, c, g, K) {
    .Call(`_sirtmm_mam_d`, y, theta, b, a, c, g, K)
}

mam_Hess <- function(y, theta, b, a, c, g, K) {
    .Call(`_sirtmm_mam_Hess`, y, theta, b, a, c, g, K)
}

mam_vec <- function(ys, theta, bs, as, cs, gs, K) {
    .Call(`_sirtmm_mam_vec`, ys, theta, bs, as, cs, gs, K)
}

EStep <- function(X, bs, as, cs, gs, K, points, weights) {
    .Call(`_sirtmm_EStep`, X, bs, as, cs, gs, K, points, weights)
}

fisherScoring <- function(bs, as, cs, gs, K, rhat, nhat, points, lambda, lambda2, maxIter = 50L) {
    .Call(`_sirtmm_fisherScoring`, bs, as, cs, gs, K, rhat, nhat, points, lambda, lambda2, maxIter)
}

EMSteps <- function(X, K, points, weights, lambda, lambda2, ngs, maxEMIter = 10L, maxNRIter = 50L, verbose = FALSE) {
    .Call(`_sirtmm_EMSteps`, X, K, points, weights, lambda, lambda2, ngs, maxEMIter, maxNRIter, verbose)
}

LogLikliTotal <- function(X, bs, as, cs, gs, K, rhat, points) {
    .Call(`_sirtmm_LogLikliTotal`, X, bs, as, cs, gs, K, rhat, points)
}

SE <- function(X, bs, as, cs, gs, K, points, weights) {
    .Call(`_sirtmm_SE`, X, bs, as, cs, gs, K, points, weights)
}

eap_theta <- function(X, bs, as, cs, gs, K, points, weights) {
    .Call(`_sirtmm_eap_theta`, X, bs, as, cs, gs, K, points, weights)
}

PSD <- function(X, thetas, bs, as, cs, gs, K, points, weights) {
    .Call(`_sirtmm_PSD`, X, thetas, bs, as, cs, gs, K, points, weights)
}

eap_theta_irt <- function(X, bs, as, cs, K, points, weights) {
    .Call(`_sirtmm_eap_theta_irt`, X, bs, as, cs, K, points, weights)
}

PSD3PL <- function(X, thetas, bs, as, cs, points, weights) {
    .Call(`_sirtmm_PSD3PL`, X, thetas, bs, as, cs, points, weights)
}

Score <- function(X, scheme) {
    .Call(`_sirtmm_Score`, X, scheme)
}

FI <- function(thetas, bs, as, cs, gs, K) {
    .Call(`_sirtmm_FI`, thetas, bs, as, cs, gs, K)
}

FI3PL <- function(thetas, bs, as, cs) {
    .Call(`_sirtmm_FI3PL`, thetas, bs, as, cs)
}

